// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `CommonService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ice.meta;

public interface CommonService extends Ice.Object,
                                       _CommonServiceOperations, _CommonServiceOperationsNC
{
    public static final String ice_staticId = "::meta::CommonService";

    public static final long serialVersionUID = -1562167472L;
}
