// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `CommonService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ice.meta;

public final class CommonServiceHolder extends Ice.ObjectHolderBase<CommonService>
{
    public
    CommonServiceHolder()
    {
    }

    public
    CommonServiceHolder(CommonService value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof CommonService)
        {
            value = (CommonService)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _CommonServiceDisp.ice_staticId();
    }
}
